[tool.poetry]
name = "railostools"
version = "1.0.0"
description = ""
authors = [" Kristian Zarębski <krizar312@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.9.0"
click = "^8.0.4"
semver = "^2.13.0"
toml = "^0.10.2"
pycountry = "^22.3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
