[tool.poetry]
name = "rostools"
version = "0.4.1"
description = "Toolkit for Railway Operation Simulator"
authors = [" Kristian Zarębski <krizar312@gmail.com>"]
license = "GPL-v3"

[tool.poetry.dependencies]
python = "^3.9"
jsbeautifier = "^1.14.0"
click = "^8.0.1"
aiofiles = "^0.7.0"
discordsdk = "^0.2.5"
toml = "^0.10.2"
pycountry = "^20.7.3"
pydantic = "^1.8.2"
semver = "^2.13.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
coverage = "^5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
rostools = 'rostools:rostools'

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py36, py37, py38, py39

[gh-actions]
python =
    3.6: py36
    3.7: py37
    3.8: py38
    3.9: py39

[testenv]
"""