name: RailOS Tools C++
on:
  - push
  - pull_request
jobs:
  build_cxx:
    name: C++ Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13.1
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1
      - name: Build Library and Tests
        run: |
          cmake -Bbuild -S cpp -G Ninja -DRAILOSTOOLS_BUILD_TESTS=ON -DRAILOSTOOLS_STATIC_LIBRARY=ON
          cmake --build build
      - name: Run Unit Tests
        run: ./build/tests/run-tests
        working-directory: cpp
