name: RailOSTools Java

on:
  - push
  - pull_request

jobs:
  build_java:
    name: Java Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run Unit Tests
        run: |
          cd java
          mvn test
