name: RailOSTools Python

on:
  - push
  - pull_request

jobs:
  build_python:
    name: Python Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Setup UV
        run: |
          python -m pip install uv
          uv venv
        working-directory: python
      - name: Run tests
        run: |
          uv run coverage run --source=railostools/ -m pytest -n auto
          uv run coverage xml
        working-directory: python
      - uses: codecov/codecov-action@v2
        with:
          file: python/coverage.xml
          flags: unittests
          name: RailOS Tools
          fail_ci_if_error: false
          verbose: true
