name: RailOSTools Python

on:
  - push
  - pull_request

jobs:
  build_python:
    name: Python Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Setup Poetry
        run: |
          python -m pip install poetry
          python -m poetry install
        working-directory: python
      - name: Run tests
        run: |
          python -m poetry run coverage run --source=railostools/ -m pytest -n auto
          python -m poetry run coverage xml
        working-directory: python
      - uses: codecov/codecov-action@v2
        with:
          file: python/coverage.xml
          flags: unittests
          name: RailOS Tools
          fail_ci_if_error: false
          verbose: true
