name: ROSTools

on:
  - push
  - pull_request

jobs:
  build_python:
    name: Python Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup Poetry
        run: |
          python -m pip install poetry
          python -m poetry install
        working-directory: python
      - name: Run tests
        run: |
          python -m poetry run coverage run --source=rostools/ -m pytest -s
          python -m poetry run coverage xml
        working-directory: python
      - uses: codecov/codecov-action@v2
        with:
          file: python/coverage.xml
          flags: unittests
          name: ROS Tools
          fail_ci_if_error: false
          verbose: true
  build_cxx:
    name: C++ Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.20.x'
      - name: Build Library and Tests
        run: |
          cmake -Bbuild
          cmake --build build --target tests
        working-directory: cpp
      - name: Run Unit Tests
        run: ./build/tests/run-tests
        working-directory: cpp
  build_java:
    name: Java Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Run Unit Tests
        run: mvn test
