name: ROSTools

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup Poetry
        run: |
          python -m pip install poetry
          python -m poetry install
      - name: Run tests
        run: |
          python -m poetry run coverage run --source=rostools/ -m pytest -s
          python -m poetry run coverage xml
      - uses: codecov/codecov-action@v2
        with:
          file: coverage.xml
          flags: unittests
          name: ROS Tools
          fail_ci_if_error: false
          verbose: true